### ISSUE TITLE
Upgrading Blammo doesn't make it more powerful, it makes it easier to play.

### ISSUE THREAD

**Issue by TerryCavanagh** [TerryCavanagh/diceydungeonsbeta#125]

**Comment by YinYin-Falcon** [comment]
I kind of expected blammo to reward fury even on triple discard - maybe that could be the upgrade.

**Comment by lcenine** [comment]
> I kind of expected blammo to reward fury even on triple discard - maybe that could be the upgrade.

That was my initial expectation. Probably a leftover impression of when the Jester first appeared and was super OP because Snap was the default status and not discard.  I'm just wondering if it wouldn't be a little strange to have one item activate on discard when no other item does. It might confuse players having different behavior...but then again I don't know of any other item that imparts a status effect when a snap 3 happens.

**Comment by TerryCavanagh** [comment]
This string is no longer used in the game!
