### ISSUE TITLE
Witch and Barter Tents

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#304]
Currently the Witch doesn't get any, since all chests work like barter for her.

However! That only applies if all spellbook slots are occupied, and there's no room to equip spells without replacing them.

Maybe on the more complicated episodes, it's worth placing a barter tent in the early game, when the spellbook isn't fully occupied yet, for that extra decision making flavor.

**Comment by TerryCavanagh** [comment]
There's something nice about the witch encountering the trader, but it's actually a huge pain to implement this (since the witch UI is implemented differently), and I'm not sure it adds much! Possibly, you could swap out one of your starting spells, but as you point out, basically all witch pickups are trades anyway. Don't think I'm gonna do this one, sorry.
