### ISSUE TITLE
Fury? and Polar Star is a tad overpowered, maybe?

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#5]
That and Copper Shield have carried me through a lot of battles with a net HP loss of zero. (Also might be compounded by the fact that Fury?'s equipment deactivation has no effect on Polar Star, since it deactivates the folllowing turn anyway.)

**Comment by TerryCavanagh** [comment]
Maybe! Polar Star is pretty excellent. Not sure how to address this right now, but I'll keep thinking about it...

**Comment by YinYin-Falcon** [comment]
Hm ... it's overpowered because the fury? penalty of being unavailable next turn doesn't change anything ...
So maybe that needs to stack. Unavailable for the next turn it would've been available for.

A card being unavailable could be a count down you can crank up, just like the flee counter.
"Available in X turns"

That might also be a slightly more interesting mechanic for some of the once-per-battle cards.

**Comment by TerryCavanagh** [comment]
That's a smart solution! I'll see about implementing it after v0.17!

**Comment by TerryCavanagh** [comment]
Nah its great actually :D
