### ISSUE TITLE
Rose modifier also affects how much damage you take from burning dice, but this isn't mentioned anywhere

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#518]

**Comment by paceheart** [comment]
If I pick up a burning dice, I take damage from my own Thorns. I would say "this is a bug" rather than "this isn't mentioned anywhere."

In this example I took 4 damage instead of 2.
![Dicey Dungeons Aug 10 08-27-36AM I take burn damage from my own thorns](https://user-images.githubusercontent.com/38589027/62823728-ec6b3880-bb48-11e9-9c80-a6e2f81ccec8.png)
Oh, I caught it a split second too late so you can't see the "-2-2" pop up.

**Comment by ncrecc** [comment]
That's Thorns. I'm talking about the "extra 1" status effect from the Rose modifier in Bonus Round.

**Comment by TerryCavanagh** [comment]
Duplicated on the main repo!
