### ISSUE TITLE
Is Jester Warrior too much like regular Warrior?

### ISSUE THREAD

**Issue by onetruepurple** [TerryCavanagh/diceydungeonsbeta#577]
Possibly an unpopular opinion. But maybe having Combat Roll in that quest makes it a bit too easy/by the numbers?

**Comment by TerryCavanagh** [comment]
I really like this episode, but I do see what you mean. It's missing a twist, of some sort. I'm planning a design pass before launch. Suggestions welcome!

**Comment by TerryCavanagh** [comment]
Good suggestions on the dicecord!
 - Split warrior abilities into smaller chunks - three separate roll cards, and maybe two short swords instead of a regular sword.
 - Probably keep Fury, though, having a high countdown in the deck throws off the balance
 - Maybe try adding a single discard button to the new skillcard (which would be a version of the usual next up card)
 - Jester Warrior booster pack suggestions:
    - Battle Axe, Nudge, Nudge
    - Broadsword, Bump, Bump
    - Short Sword, Short Sword, Juggling Ball
    - Claw, Claw, Spare 3

**Comment by TerryCavanagh** [comment]
Ok! I've made some changes here which I'll test out soon.
