### ISSUE TITLE
Trader doesn't understand how Jester works

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#71]
![](https://i.frogbox.es/lpo)

- Cards are not shown as 1x2
- Shopkeeper always claims you have a finale card regardless of what the available trade is
- Upgraded cards offered are not presented as Jester-friendly variants (this Battle Axe+ would be MAX5 if I got it by upgrading Battle Axe normally)

**Comment by ncrecc** [comment]
Yeah, still here. Just this time shopkeeper says nothing about a finale card.

**Comment by paceheart** [comment]
Val offers Jester Hammer+ instead of Hammer+ (deck upgraded version) in exchange for Boomerang+.

![Dicey Dungeons Aug 04 08-35-46AM hammer+ deck upgraded version](https://user-images.githubusercontent.com/38589027/62425920-889dc700-b693-11e9-981a-09362473e6d9.png)

I'm going to take one for the team and make the trade to see what happens.

![Dicey Dungeons Aug 04 08-38-08AM hammer+](https://user-images.githubusercontent.com/38589027/62425922-8b002100-b693-11e9-8a4e-02739645d059.png)

I got Hammer+ instead of Hammer+ (deck upgraded version). Hammer+ (deck upgraded version) is supposed to be the card on the right, here:
https://cdn.discordapp.com/attachments/552131784939405332/607598617834029090/unknown.png

**Comment by paceheart** [comment]
Saving and loading turns it into Hammer+ (deck upgraded version).

![Dicey Dungeons Aug 04 08-50-11AM save and load](https://user-images.githubusercontent.com/38589027/62426065-e67ede80-b694-11e9-996e-27e92b6f02f2.png)

**Comment by TerryCavanagh** [comment]
Yep, still here, though there's a new issue for this on the main repo, so can close this one!
