### ISSUE TITLE
Freeze? only seems to affect the first dice you roll as PU Robot

### ISSUE THREAD

**Issue by ncrecc** [TerryCavanagh/diceydungeonsbeta#79]

**Comment by onetruepurple** [comment]
Note: does not affect Yeti's Freeze All

**Comment by paceheart** [comment]
I think it's a bit more complicated than that. Frozen? is counterintuitive for Robot. I had Frozen? 3, and I rolled a 6 that turned into a 5, then I rolled a 2 and that turned my dice into 4 1, and now I'm unfrozen. That's what I would have expected from Frozen? 1, because it's supposed to lower all your dice by 1, right? So I would have expected Frozen? 3 to lower all my dice by 3.

**Comment by TerryCavanagh** [comment]
Should be fixed in today's beta. Thanks!
